WORKSPACE: Update datascience-notebook
To get the latest version of R, based on the error:
```
* checking for file ‘/tmp/RtmpXHpmQy/file3c0c5fa77527/rethinking/DESCRIPTION’ ... OK
* preparing ‘rethinking’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘rethinking_2.13.tar.gz’

* installing *source* package ‘rethinking’ ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rethinking)
> library(rethinking)
Loading required package: rstan
Loading required package: StanHeaders
Loading required package: ggplot2
Error: package or namespace load failed for ‘ggplot2’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.12 is already loaded, but >= 1.0.2 is required
Error: package ‘ggplot2’ could not be loaded
Execution halted
```